# Generated by Django 5.2 on 2025-05-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='duracion',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
    ]
