# Generated by Django 5.2 on 2025-05-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_elemento_duracion_alter_elemento_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='elementos_fotos/'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='ubicacion',
            field=models.CharField(default='Sin ubicación', max_length=100),
        ),
    ]
